name: Security Scan

on:
  workflow_call:

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Detect secrets
        uses: trufflesecurity/trufflehog@v3.82.2
        with:
          path: ./
          base: main
          head: HEAD
          extra_args: --only-verified
